language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: hCiQxTCMNLuGotbGDdtE4d6fBaiTYdHOtT2uqpKZi4pm/fO6iW+Me4XoFGBhCiXkOVBmP64VFIRHkIQqjA9BNteFMxTuGG1sCKr43pvoGBWjGlRwzBBsgaUKSY3xBl4VVpxP566DDgOjbJk/ytwR/Bkaaot1UGVvaGmY+7MEZ4w0JxXKLTZawRJyAsMPLkVy7PS13o9hGgbz3F8Ot0RbI+z2gtao2FpK0ghULU576z4xjTs0ruNarDca2A3BCfVyqQ9eoNSZQ5bd1onXDvOYtIsMAYvTpyWi11/uHY6NoXa2Q0AnWsO6/9FPpgMcj1WiOe/CXh4CfY5lZu02N6AEPadmbngMD54V+fy32MH3cvXVCjmoKHGAwFM4LNO9Ba43/bOy6N6wPHWIXd7VTcZHcK1SRHT4Q4AqGlK5tfYZcujqOyARe+JQB+DS9y/hFL7ln3A3uCLU2062r0NR4rJ3CgX23xuFrMV8Kre34+bCqvo5MVypy4euL7922iCqCrpYj2TkwAA5WH9omYqKJg4iNsg8Vnd90XPlXgq+0bB1mXfpfUi0bnEGHxqc+cbfiT/57EwSZgnhMbXZUKx+3cz+QV7SOO5Sh5htIijT0QyPV86QVOnXF8LNrYT10tn7XsmvPufEWPrM7iAP+C7T0hlmsWpzYJ+q0xaH5ILW+OrlMcs=
  app: cryptic-ocean-96796