language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: JpESPi/PAfUrB4DUtjeJruta1XqTam55sKpawGDVtCRDwdVJu4DqRNqAOKYuRZ7wyyiEBJM/rtUILgFVborCwwSBziTX4S3JMSaZnOzoIs0KJL6khU5dRqrRntTNIx5AJrfB0GI4pzg4t9hTJ8vUNpO4FkBz26pPwt9JRKL/SAxSSNan4e1as0EFRgYe47zE5V+C9vfd8nTblz4Bu/A478t1ctLtkJTSem0q49RvoS/C/cp0SS6LnJwNXohycmgU4RoZI1wYpfV3ENC9ya9i9CrKPyaUlidTpzlZ0BnDwQ4s2L+llfWUZtFAMt22DbZBw9F9j8SX7PAswG28QcLGWgCS+Ka38uB98y4mYAhB4waD5UbSPp1W0yASoi1tyGwy3KzefvK+0eLMDtJ7lxSMD9im4XmuQsYpuIT7t8zhFGUyhBYDRlDWn/BABCsF6nH/x0X7Hs8tqn5B+vRmD3BHxOJsrrUhft4a8Tu/XHu4401mklC9WilvkZ7ShP+EffnJzgMC28xFufs5r/NPvu/iryGxgCg/mNRI0393x2KTd15f/ecnuE6KRbN0w1yeh+oOGnVUe0apXj/wqKxh0h41N7BgrJb1fh5Sh2NPl53XLcxNi8YGZXRpzfetQA0tsBg6Q4m7gUNaIK8vtKitfe0unbtDrHRT0Y1IpJckAJAIeqA=
  app: cryptic-ocean-96796
