language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: 0v6D4I109k31NYxPsn96+iX8aVLZPwFHACYYPn+i+atyhGMLDKpYsCiue6lqLVyzRgE0OelQiNXHAv5s5OtkefNeJ8In80sGSB+hcnPfuBF+wyBuxlbclT/yNSF+6HEQGFUBu/CePjBp6bKI8tVNA4WjJT8nXOuBMzr+Cp8QmMJEq3KBL7g0Lxy7y5lDDoB0919r/d0D3MkSS692vJpID9uvJ6ETrIc72UDHYoSLbcqCcUQ6sDPXtmF7FTfgbFMDKq3TkD5D11YWYHIWYO/pLHWk+BWagUbMgclsK+zLRPCakf1W85zgRzG1SW6l6OyVxK7gWjZC8vUtSM16h8Y2/YS6Dj6VCI+pTEWCg9IyPX4zuk4Wf6ywo5UIu6XfWC7IWE6RC3UzDp/sW96zbSZjH6UySu9hYjDA/JEogr+zUsQVCJSJOsxxTXMJj8m4nEYgFAu62MRQPBB4bXQtTAb5mvrC8JUNAtW/3F9rGq5N+NmaZAZxmjjgJDQkobJtwpJmZ5G9aBnz5F/SiMAaE7Bayyo+qx0CnKiUiLXaJ73RbVVdLCWM0uhCjnQhaPtP+PUCxo9ilCafcC/cMkVos9s+Qaftj6KKAHdhVGyqZZ84YL4TjQlBtFvFtromS0DDTS9Makg/boDhjMUkY2RP6HFhFO9fyZ2qSXdMmsz4dReNbuM=
  app: cryptic-ocean-96796
