language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: uq3STIBD4k0SZe49Rhxzv1Fzq/GYJHDu9UksHST0Z0ewANVSECzcPNGL631AACRSQJSDZxuwQDa0JVUrTOBLMWXWOXyBYsg9GBAi0eQC/WRc+YRJsfcOeJWOOC+uEXinkYOSApVvVV3m0oCXKSfORV2pfC1Zyx/560tGYTfSCXPjj+h0CAYM0dtppM8/UnxaGseDUtQbapFEusfxbKdq4I9iWd4r91vFsmAFosQjjAMPmhIkuHiwuRB9UMRFFLAOPhiwFtsWJ3W70ZCpdA8xR3+nIHX1cJKHD+SwLDlTr65OXavrHpHexN9WEPhLj7xpgfFD4tXN86DzDoll36z9iqV5HdzVmeb6epGO1TPbHi7/fzdYU2QWLQPh9/WFsnjEvv+9D3amdONhIpVAAYK1lg7Pq0PuQZ5tEo25eq7yT0wSpdar2IqJOOd86TCo43M24bnjq6YLRRufDgFTkio96z6zHrlo7AptNgMPC5oyUFVaBO7jUpr5+nH8s/X6CW05E1HEpQYEy1+RB3IAbTCuPOzTy37rUdm5lUBxtbab5fWk4U+8E+LZSnNiG3uuwLzxz8eBJW32YwZVBodoSVbaaR4S5jYZ7pN7i3CThi3MLK3nef+bIjMbwwN1hY6CnVZsh1kkbnotT4MsbY+HEH8Zf6C1EDJxCCjOMGW1/Sl5fnM=
  app: cryptic-ocean-96796
